using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SageOneApi.Models;

namespace SageOneApi.Tests
{
	/// <summary>
	/// Use these tests to populate your developer account with sample data.
	/// Data used are from the sample Northwind database : https://northwinddatabase.codeplex.com/
	/// </summary>
	[TestClass]
	public class SampleDataCreate : TestBase
	{
		#region Suppliers

		[TestMethod]
		public void CreateSuppliers()
		{
			var suppliers = new List<Supplier>
			{
				new Supplier{Name = "Exotic Liquids",ContactName = "Charlotte Cooper",DeliveryAddress01 = "49 Gilbert St.",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "EC1 4SD",DeliveryAddress05 = "UK",Telephone = "(171) 555-2222",Fax = ""},
				new Supplier{Name = "New Orleans Cajun Delights",ContactName = "Shelley Burke",DeliveryAddress01 = "P.O. Box 78934",DeliveryAddress02 = "New Orleans",DeliveryAddress03 = "LA",DeliveryAddress04 = "70117",DeliveryAddress05 = "USA",Telephone = "(100) 555-4822",Fax = ""},
				new Supplier{Name = "Grandma Kelly's Homestead",ContactName = "Regina Murphy",DeliveryAddress01 = "707 Oxford Rd.",DeliveryAddress02 = "Ann Arbor",DeliveryAddress03 = "MI",DeliveryAddress04 = "48104",DeliveryAddress05 = "USA",Telephone = "(313) 555-5735",Fax = "(313) 555-3349"},
				new Supplier{Name = "Tokyo Traders",ContactName = "Yoshi Nagase",DeliveryAddress01 = "9-8 Sekimai Musashino-shi",DeliveryAddress02 = "Tokyo",DeliveryAddress03 = "",DeliveryAddress04 = "100",DeliveryAddress05 = "Japan",Telephone = "(03) 3555-5011",Fax = ""},
				new Supplier{Name = "Cooperativa de Quesos 'Las Cabras'",ContactName = "Antonio del Valle Saavedra",DeliveryAddress01 = "Calle del Rosal 4",DeliveryAddress02 = "Oviedo",DeliveryAddress03 = "Asturias",DeliveryAddress04 = "33007",DeliveryAddress05 = "Spain",Telephone = "(98) 598 76 54",Fax = ""},
				new Supplier{Name = "Mayumi's",ContactName = "Mayumi Ohno",DeliveryAddress01 = "92 Setsuko Chuo-ku",DeliveryAddress02 = "Osaka",DeliveryAddress03 = "",DeliveryAddress04 = "545",DeliveryAddress05 = "Japan",Telephone = "(06) 431-7877",Fax = ""},
				new Supplier{Name = "Pavlova, Ltd.",ContactName = "Ian Devling",DeliveryAddress01 = "74 Rose St. Moonie Ponds",DeliveryAddress02 = "Melbourne",DeliveryAddress03 = "Victoria",DeliveryAddress04 = "3058",DeliveryAddress05 = "Australia",Telephone = "(03) 444-2343",Fax = "(03) 444-6588"},
				new Supplier{Name = "Specialty Biscuits, Ltd.",ContactName = "Peter Wilson",DeliveryAddress01 = "29 King's Way",DeliveryAddress02 = "Manchester",DeliveryAddress03 = "",DeliveryAddress04 = "M14 GSD",DeliveryAddress05 = "UK",Telephone = "(161) 555-4448",Fax = ""},
				new Supplier{Name = "PB Knäckebröd AB",ContactName = "Lars Peterson",DeliveryAddress01 = "Kaloadagatan 13",DeliveryAddress02 = "Göteborg",DeliveryAddress03 = "",DeliveryAddress04 = "S-345 67",DeliveryAddress05 = "Sweden",Telephone = "031-987 65 43",Fax = "031-987 65 91"},
				new Supplier{Name = "Refrescos Americanas LTDA",ContactName = "Carlos Diaz",DeliveryAddress01 = "Av. das Americanas 12.890",DeliveryAddress02 = "Sao Paulo",DeliveryAddress03 = "",DeliveryAddress04 = "5442",DeliveryAddress05 = "Brazil",Telephone = "(11) 555 4640",Fax = ""},
				new Supplier{Name = "Heli Süßwaren GmbH & Co. KG",ContactName = "Petra Winkler",DeliveryAddress01 = "Tiergartenstraße 5",DeliveryAddress02 = "Berlin",DeliveryAddress03 = "",DeliveryAddress04 = "10785",DeliveryAddress05 = "Germany",Telephone = "(010) 9984510",Fax = ""},
				new Supplier{Name = "Plutzer Lebensmittelgroßmärkte AG",ContactName = "Martin Bein",DeliveryAddress01 = "Bogenallee 51",DeliveryAddress02 = "Frankfurt",DeliveryAddress03 = "",DeliveryAddress04 = "60439",DeliveryAddress05 = "Germany",Telephone = "(069) 992755",Fax = ""},
				new Supplier{Name = "Nord-Ost-Fisch Handelsgesellschaft mbH",ContactName = "Sven Petersen",DeliveryAddress01 = "Frahmredder 112a",DeliveryAddress02 = "Cuxhaven",DeliveryAddress03 = "",DeliveryAddress04 = "27478",DeliveryAddress05 = "Germany",Telephone = "(04721) 8713",Fax = "(04721) 8714"},
				new Supplier{Name = "Formaggi Fortini s.r.l.",ContactName = "Elio Rossi",DeliveryAddress01 = "Viale Dante, 75",DeliveryAddress02 = "Ravenna",DeliveryAddress03 = "",DeliveryAddress04 = "48100",DeliveryAddress05 = "Italy",Telephone = "(0544) 60323",Fax = "(0544) 60603"},
				new Supplier{Name = "Norske Meierier",ContactName = "Beate Vileid",DeliveryAddress01 = "Hatlevegen 5",DeliveryAddress02 = "Sandvika",DeliveryAddress03 = "",DeliveryAddress04 = "1320",DeliveryAddress05 = "Norway",Telephone = "(0)2-953010",Fax = ""},
				new Supplier{Name = "Bigfoot Breweries",ContactName = "Cheryl Saylor",DeliveryAddress01 = "3400 - 8th Avenue Suite 210",DeliveryAddress02 = "Bend",DeliveryAddress03 = "OR",DeliveryAddress04 = "97101",DeliveryAddress05 = "USA",Telephone = "(503) 555-9931",Fax = ""},
				new Supplier{Name = "Svensk Sjöföda AB",ContactName = "Michael Björn",DeliveryAddress01 = "Brovallavägen 231",DeliveryAddress02 = "Stockholm",DeliveryAddress03 = "",DeliveryAddress04 = "S-123 45",DeliveryAddress05 = "Sweden",Telephone = "08-123 45 67",Fax = ""},
				new Supplier{Name = "Aux joyeux ecclésiastiques",ContactName = "Guylène Nodier",DeliveryAddress01 = "203, Rue des Francs-Bourgeois",DeliveryAddress02 = "Paris",DeliveryAddress03 = "",DeliveryAddress04 = "75004",DeliveryAddress05 = "France",Telephone = "(1) 03.83.00.68",Fax = "(1) 03.83.00.62"},
				new Supplier{Name = "New England Seafood Cannery",ContactName = "Robb Merchant",DeliveryAddress01 = "Order Processing Dept. 2100 Paul Revere Blvd.",DeliveryAddress02 = "Boston",DeliveryAddress03 = "MA",DeliveryAddress04 = "2134",DeliveryAddress05 = "USA",Telephone = "(617) 555-3267",Fax = "(617) 555-3389"},
				new Supplier{Name = "Leka Trading",ContactName = "Chandra Leka",DeliveryAddress01 = "471 Serangoon Loop, Suite #402",DeliveryAddress02 = "Singapore",DeliveryAddress03 = "",DeliveryAddress04 = "512",DeliveryAddress05 = "Singapore",Telephone = "555-8787",Fax = ""},
				new Supplier{Name = "Lyngbysild",ContactName = "Niels Petersen",DeliveryAddress01 = "Lyngbysild Fiskebakken 10",DeliveryAddress02 = "Lyngby",DeliveryAddress03 = "",DeliveryAddress04 = "2800",DeliveryAddress05 = "Denmark",Telephone = "43844108",Fax = "43844115"},
				new Supplier{Name = "Zaanse Snoepfabriek",ContactName = "Dirk Luchte",DeliveryAddress01 = "Verkoop Rijnweg 22",DeliveryAddress02 = "Zaandam",DeliveryAddress03 = "",DeliveryAddress04 = "9999 ZZ",DeliveryAddress05 = "Netherlands",Telephone = "(12345) 1212",Fax = "(12345) 1210"},
				new Supplier{Name = "Karkki Oy",ContactName = "Anne Heikkonen",DeliveryAddress01 = "Valtakatu 12",DeliveryAddress02 = "Lappeenranta",DeliveryAddress03 = "",DeliveryAddress04 = "53120",DeliveryAddress05 = "Finland",Telephone = "(953) 10956",Fax = ""},
				new Supplier{Name = "G'day, Mate",ContactName = "Wendy Mackenzie",DeliveryAddress01 = "170 Prince Edward Parade Hunter's Hill",DeliveryAddress02 = "Sydney",DeliveryAddress03 = "NSW",DeliveryAddress04 = "2042",DeliveryAddress05 = "Australia",Telephone = "(02) 555-5914",Fax = "(02) 555-4873"},
				new Supplier{Name = "Ma Maison",ContactName = "Jean-Guy Lauzon",DeliveryAddress01 = "2960 Rue St. Laurent",DeliveryAddress02 = "Montréal",DeliveryAddress03 = "Québec",DeliveryAddress04 = "H1J 1C3",DeliveryAddress05 = "Canada",Telephone = "(514) 555-9022",Fax = ""},
				new Supplier{Name = "Pasta Buttini s.r.l.",ContactName = "Giovanni Giudici",DeliveryAddress01 = "Via dei Gelsomini, 153",DeliveryAddress02 = "Salerno",DeliveryAddress03 = "",DeliveryAddress04 = "84100",DeliveryAddress05 = "Italy",Telephone = "(089) 6547665",Fax = "(089) 6547667"},
				new Supplier{Name = "Escargots Nouveaux",ContactName = "Marie Delamare",DeliveryAddress01 = "22, rue H. Voiron",DeliveryAddress02 = "Montceau",DeliveryAddress03 = "",DeliveryAddress04 = "71300",DeliveryAddress05 = "France",Telephone = "85.57.00.07",Fax = ""},
				new Supplier{Name = "Gai pâturage",ContactName = "Eliane Noz",DeliveryAddress01 = "Bat. B 3, rue des Alpes",DeliveryAddress02 = "Annecy",DeliveryAddress03 = "",DeliveryAddress04 = "74000",DeliveryAddress05 = "France",Telephone = "38.76.98.06",Fax = "38.76.98.58"},
				new Supplier{Name = "Forêts d'érables",ContactName = "Chantal Goulet",DeliveryAddress01 = "148 rue Chasseur",DeliveryAddress02 = "Ste-Hyacinthe",DeliveryAddress03 = "Québec",DeliveryAddress04 = "J2S 7S8",DeliveryAddress05 = "Canada",Telephone = "(514) 555-2955",Fax = "(514) 555-2921"}
			};
			var api = new ApiRequest(Username, Password, Apikey, CompanyId);

			foreach (var supplier in suppliers)
			{
				supplier.PostalAddress01 = supplier.DeliveryAddress01;
				supplier.PostalAddress02 = supplier.DeliveryAddress02;
				supplier.PostalAddress03 = supplier.DeliveryAddress03;
				supplier.PostalAddress04 = supplier.DeliveryAddress04;
				supplier.PostalAddress05 = supplier.DeliveryAddress05;
			}

			suppliers.ForEach(supplier => api.SupplierRequest.Save(supplier));
		}

		#endregion

		#region Items / Item Categories

		#region Item Categories

		[TestMethod]
		public void CreateItemCategories()
		{
			var itemCategories = new List<Category>
			{
				new Category { Description = "Beverages" },
				new Category { Description = "Condiments" },
				new Category { Description = "Confections" },
				new Category { Description = "Dairy Products" },
				new Category { Description = "Grains/Cereals" },
				new Category { Description = "Meat/Poultry" },
				new Category { Description = "Produce" },
				new Category { Description = "Seafood" }
			};

			var api = new ApiRequest(Username, Password, Apikey, CompanyId);
			itemCategories.ForEach(cat => api.CategoryRequest.Save(cat, Enums.CategoryType.Item));
		}

		#endregion

		#region Items

		[TestMethod]
		public void CreateItems()
		{
			var api = new ApiRequest(Username, Password, Apikey, CompanyId);

			var categories = api.CategoryRequest.Get(Enums.CategoryType.Item).Results;
			var beverages = categories.Find(r => r.Description == "Beverages");
			var condiments = categories.Find(r => r.Description == "Condiments");
			var confections = categories.Find(r => r.Description == "Confections");
			var dairyProducts = categories.Find(r => r.Description == "Dairy Products");
			var grainsCereals = categories.Find(r => r.Description == "Grains/Cereals");
			var meatPoultry = categories.Find(r => r.Description == "Meat/Poultry");
			var produce = categories.Find(r => r.Description == "Produce");
			var seafood = categories.Find(r => r.Description == "Seafood");

			var items = new List<Item>
			{
				new Item { Code = "Chai", Description = "Chai - 10 boxes x 20 bags",PriceInclusive  = 180,PriceExclusive = 180, QuantityOnHand = 39, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Chang", Description = "Chang - 24 - 12 oz bottles",PriceInclusive  = 190,PriceExclusive = 190, QuantityOnHand = 17, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Aniseed Syrup", Description = "Aniseed Syrup - 12 - 550 ml bottles",PriceInclusive  = 100,PriceExclusive = 100, QuantityOnHand = 13, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Chef Anton's Cajun Seasoning", Description = "Chef Anton's Cajun Seasoning - 48 - 6 oz jars",PriceInclusive  = 220,PriceExclusive = 220, QuantityOnHand = 53, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Chef Anton's Gumbo Mix", Description = "Chef Anton's Gumbo Mix - 36 boxes",PriceInclusive  = 213.5m,PriceExclusive = 213.5m, QuantityOnHand = 0, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Grandma's Boysenberry Spread", Description = "Grandma's Boysenberry Spread - 12 - 8 oz jars",PriceInclusive  = 250,PriceExclusive = 250, QuantityOnHand = 120, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Uncle Bob's Organic Dried Pears", Description = "Uncle Bob's Organic Dried Pears - 12 - 1 lb pkgs.",PriceInclusive  = 300,PriceExclusive = 300, QuantityOnHand = 15, Category = produce, Active = true, Physical = true},
				new Item { Code = "Northwoods Cranberry Sauce", Description = "Northwoods Cranberry Sauce - 12 - 12 oz jars",PriceInclusive  = 400,PriceExclusive = 400, QuantityOnHand = 6, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Mishi Kobe Niku", Description = "Mishi Kobe Niku - 18 - 500 g pkgs.",PriceInclusive  = 970,PriceExclusive = 970, QuantityOnHand = 29, Category = meatPoultry, Active = true, Physical = true},
				new Item { Code = "Ikura", Description = "Ikura - 12 - 200 ml jars",PriceInclusive  = 310,PriceExclusive = 310, QuantityOnHand = 31, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Queso Cabrales", Description = "Queso Cabrales - 1 kg pkg.",PriceInclusive  = 210,PriceExclusive = 210, QuantityOnHand = 22, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Queso Manchego La Pastora", Description = "Queso Manchego La Pastora - 10 - 500 g pkgs.",PriceInclusive  = 380,PriceExclusive = 380, QuantityOnHand = 86, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Konbu", Description = "Konbu - 2 kg box",PriceInclusive  = 60,PriceExclusive = 60, QuantityOnHand = 24, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Tofu", Description = "Tofu - 40 - 100 g pkgs.",PriceInclusive  = 232.5m,PriceExclusive = 232.5m, QuantityOnHand = 35, Category = produce, Active = true, Physical = true},
				new Item { Code = "Genen Shouyu", Description = "Genen Shouyu - 24 - 250 ml bottles",PriceInclusive  = 155,PriceExclusive = 155, QuantityOnHand = 39, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Pavlova", Description = "Pavlova - 32 - 500 g boxes",PriceInclusive  = 174.5m,PriceExclusive = 174.5m, QuantityOnHand = 29, Category = confections, Active = true, Physical = true},
				new Item { Code = "Alice Mutton", Description = "Alice Mutton - 20 - 1 kg tins",PriceInclusive  = 390,PriceExclusive = 390, QuantityOnHand = 0, Category = meatPoultry, Active = true, Physical = true},
				new Item { Code = "Carnarvon Tigers", Description = "Carnarvon Tigers - 16 kg pkg.",PriceInclusive  = 625,PriceExclusive = 625, QuantityOnHand = 42, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Teatime Chocolate Biscuits", Description = "Teatime Chocolate Biscuits - 10 boxes x 12 pieces",PriceInclusive  = 92,PriceExclusive = 92, QuantityOnHand = 25, Category = confections, Active = true, Physical = true},
				new Item { Code = "Sir Rodney's Marmalade", Description = "Sir Rodney's Marmalade - 30 gift boxes",PriceInclusive  = 810,PriceExclusive = 810, QuantityOnHand = 40, Category = confections, Active = true, Physical = true},
				new Item { Code = "Sir Rodney's Scones", Description = "Sir Rodney's Scones - 24 pkgs. x 4 pieces",PriceInclusive  = 100,PriceExclusive = 100, QuantityOnHand = 3, Category = confections, Active = true, Physical = true},
				new Item { Code = "Gustaf's Knäckebröd", Description = "Gustaf's Knäckebröd - 24 - 500 g pkgs.",PriceInclusive  = 210,PriceExclusive = 210, QuantityOnHand = 104, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Tunnbröd", Description = "Tunnbröd - 12 - 250 g pkgs.",PriceInclusive  = 90,PriceExclusive = 90, QuantityOnHand = 61, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Guaraná Fantástica", Description = "Guaraná Fantástica - 12 - 355 ml cans",PriceInclusive  = 45,PriceExclusive = 45, QuantityOnHand = 20, Category = beverages, Active = true, Physical = true},
				new Item { Code = "NuNuCa Nuß-Nougat-Creme", Description = "NuNuCa Nuß-Nougat-Creme - 20 - 450 g glasses",PriceInclusive  = 140,PriceExclusive = 140, QuantityOnHand = 76, Category = confections, Active = true, Physical = true},
				new Item { Code = "Gumbär Gummibärchen", Description = "Gumbär Gummibärchen - 100 - 250 g bags",PriceInclusive  = 312.3m,PriceExclusive = 312.3m, QuantityOnHand = 15, Category = confections, Active = true, Physical = true},
				new Item { Code = "Schoggi Schokolade", Description = "Schoggi Schokolade - 100 - 100 g pieces",PriceInclusive  = 439,PriceExclusive = 439, QuantityOnHand = 49, Category = confections, Active = true, Physical = true},
				new Item { Code = "Rössle Sauerkraut", Description = "Rössle Sauerkraut - 25 - 825 g cans",PriceInclusive  = 456,PriceExclusive = 456, QuantityOnHand = 26, Category = produce, Active = true, Physical = true},
				new Item { Code = "Thüringer Rostbratwurst", Description = "Thüringer Rostbratwurst - 50 bags x 30 sausgs.",PriceInclusive  = 1237.9m,PriceExclusive = 1237.9m, QuantityOnHand = 0, Category = meatPoultry, Active = true, Physical = true},
				new Item { Code = "Nord-Ost Matjeshering", Description = "Nord-Ost Matjeshering - 10 - 200 g glasses",PriceInclusive  = 258.9m,PriceExclusive = 258.9m, QuantityOnHand = 10, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Gorgonzola Telino", Description = "Gorgonzola Telino - 12 - 100 g pkgs",PriceInclusive  = 125,PriceExclusive = 125, QuantityOnHand = 0, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Mascarpone Fabioli", Description = "Mascarpone Fabioli - 24 - 200 g pkgs.",PriceInclusive  = 320,PriceExclusive = 320, QuantityOnHand = 9, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Geitost", Description = "Geitost - 500 g",PriceInclusive  = 25,PriceExclusive = 25, QuantityOnHand = 112, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Sasquatch Ale", Description = "Sasquatch Ale - 24 - 12 oz bottles",PriceInclusive  = 140,PriceExclusive = 140, QuantityOnHand = 111, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Steeleye Stout", Description = "Steeleye Stout - 24 - 12 oz bottles",PriceInclusive  = 180,PriceExclusive = 180, QuantityOnHand = 20, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Inlagd Sill", Description = "Inlagd Sill - 24 - 250 g  jars",PriceInclusive  = 190,PriceExclusive = 190, QuantityOnHand = 112, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Gravad lax", Description = "Gravad lax - 12 - 500 g pkgs.",PriceInclusive  = 260,PriceExclusive = 260, QuantityOnHand = 11, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Côte de Blaye", Description = "Côte de Blaye - 12 - 75 cl bottles",PriceInclusive  = 2635,PriceExclusive = 2635, QuantityOnHand = 17, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Chartreuse verte", Description = "Chartreuse verte - 750 cc per bottle",PriceInclusive  = 180,PriceExclusive = 180, QuantityOnHand = 69, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Boston Crab Meat", Description = "Boston Crab Meat - 24 - 4 oz tins",PriceInclusive  = 184,PriceExclusive = 184, QuantityOnHand = 123, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Jack's New England Clam Chowder", Description = "Jack's New England Clam Chowder - 12 - 12 oz cans",PriceInclusive  = 96.5m,PriceExclusive = 96.5m, QuantityOnHand = 85, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Singaporean Hokkien Fried Mee", Description = "Singaporean Hokkien Fried Mee - 32 - 1 kg pkgs.",PriceInclusive  = 140,PriceExclusive = 140, QuantityOnHand = 26, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Ipoh Coffee", Description = "Ipoh Coffee - 16 - 500 g tins",PriceInclusive  = 460,PriceExclusive = 460, QuantityOnHand = 17, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Gula Malacca", Description = "Gula Malacca - 20 - 2 kg bags",PriceInclusive  = 194.5m,PriceExclusive = 194.5m, QuantityOnHand = 27, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Rogede sild", Description = "Rogede sild - 1k pkg.",PriceInclusive  = 95,PriceExclusive = 95, QuantityOnHand = 5, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Spegesild", Description = "Spegesild - 4 - 450 g glasses",PriceInclusive  = 120,PriceExclusive = 120, QuantityOnHand = 95, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Zaanse koeken", Description = "Zaanse koeken - 10 - 4 oz boxes",PriceInclusive  = 95,PriceExclusive = 95, QuantityOnHand = 36, Category = confections, Active = true, Physical = true},
				new Item { Code = "Chocolade", Description = "Chocolade - 10 pkgs.",PriceInclusive  = 127.5m,PriceExclusive = 127.5m, QuantityOnHand = 15, Category = confections, Active = true, Physical = true},
				new Item { Code = "Maxilaku", Description = "Maxilaku - 24 - 50 g pkgs.",PriceInclusive  = 200,PriceExclusive = 200, QuantityOnHand = 10, Category = confections, Active = true, Physical = true},
				new Item { Code = "Valkoinen suklaa", Description = "Valkoinen suklaa - 12 - 100 g bars",PriceInclusive  = 162.5m,PriceExclusive = 162.5m, QuantityOnHand = 65, Category = confections, Active = true, Physical = true},
				new Item { Code = "Manjimup Dried Apples", Description = "Manjimup Dried Apples - 50 - 300 g pkgs.",PriceInclusive  = 530,PriceExclusive = 530, QuantityOnHand = 20, Category = produce, Active = true, Physical = true},
				new Item { Code = "Filo Mix", Description = "Filo Mix - 16 - 2 kg boxes",PriceInclusive  = 70,PriceExclusive = 70, QuantityOnHand = 38, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Perth Pasties", Description = "Perth Pasties - 48 pieces",PriceInclusive  = 328,PriceExclusive = 328, QuantityOnHand = 0, Category = meatPoultry, Active = true, Physical = true},
				new Item { Code = "Tourtière", Description = "Tourtière - 16 pies",PriceInclusive  = 74.5m,PriceExclusive = 74.5m, QuantityOnHand = 21, Category = meatPoultry, Active = true, Physical = true},
				new Item { Code = "Pâté chinois", Description = "Pâté chinois - 24 boxes x 2 pies",PriceInclusive  = 240,PriceExclusive = 240, QuantityOnHand = 115, Category = meatPoultry, Active = true, Physical = true},
				new Item { Code = "Gnocchi di nonna Alice", Description = "Gnocchi di nonna Alice - 24 - 250 g pkgs.",PriceInclusive  = 380,PriceExclusive = 380, QuantityOnHand = 21, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Ravioli Angelo", Description = "Ravioli Angelo - 24 - 250 g pkgs.",PriceInclusive  = 195,PriceExclusive = 195, QuantityOnHand = 36, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Escargots de Bourgogne", Description = "Escargots de Bourgogne - 24 pieces",PriceInclusive  = 132.5m,PriceExclusive = 132.5m, QuantityOnHand = 62, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Raclette Courdavault", Description = "Raclette Courdavault - 5 kg pkg.",PriceInclusive  = 550,PriceExclusive = 550, QuantityOnHand = 79, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Camembert Pierrot", Description = "Camembert Pierrot - 15 - 300 g rounds",PriceInclusive  = 340,PriceExclusive = 340, QuantityOnHand = 19, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Sirop d'érable", Description = "Sirop d'érable - 24 - 500 ml bottles",PriceInclusive  = 285,PriceExclusive = 285, QuantityOnHand = 113, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Tarte au sucre", Description = "Tarte au sucre - 48 pies",PriceInclusive  = 493,PriceExclusive = 493, QuantityOnHand = 17, Category = confections, Active = true, Physical = true},
				new Item { Code = "Vegie-spread", Description = "Vegie-spread - 15 - 625 g jars",PriceInclusive  = 439,PriceExclusive = 439, QuantityOnHand = 24, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Wimmers gute Semmelknödel", Description = "Wimmers gute Semmelknödel - 20 bags x 4 pieces",PriceInclusive  = 332.5m,PriceExclusive = 332.5m, QuantityOnHand = 22, Category = grainsCereals, Active = true, Physical = true},
				new Item { Code = "Louisiana Fiery Hot Pepper Sauce", Description = "Louisiana Fiery Hot Pepper Sauce - 32 - 8 oz bottles",PriceInclusive  = 210.5m,PriceExclusive = 210.5m, QuantityOnHand = 76, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Louisiana Hot Spiced Okra", Description = "Louisiana Hot Spiced Okra - 24 - 8 oz jars",PriceInclusive  = 170,PriceExclusive = 170, QuantityOnHand = 4, Category = condiments, Active = true, Physical = true},
				new Item { Code = "Laughing Lumberjack Lager", Description = "Laughing Lumberjack Lager - 24 - 12 oz bottles",PriceInclusive  = 140,PriceExclusive = 140, QuantityOnHand = 52, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Scottish Longbreads", Description = "Scottish Longbreads - 10 boxes x 8 pieces",PriceInclusive  = 125,PriceExclusive = 125, QuantityOnHand = 6, Category = confections, Active = true, Physical = true},
				new Item { Code = "Gudbrandsdalsost", Description = "Gudbrandsdalsost - 10 kg pkg.",PriceInclusive  = 360,PriceExclusive = 360, QuantityOnHand = 26, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Outback Lager", Description = "Outback Lager - 24 - 355 ml bottles",PriceInclusive  = 150,PriceExclusive = 150, QuantityOnHand = 15, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Flotemysost", Description = "Flotemysost - 10 - 500 g pkgs.",PriceInclusive  = 215,PriceExclusive = 215, QuantityOnHand = 26, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Mozzarella di Giovanni", Description = "Mozzarella di Giovanni - 24 - 200 g pkgs.",PriceInclusive  = 348,PriceExclusive = 348, QuantityOnHand = 14, Category = dairyProducts, Active = true, Physical = true},
				new Item { Code = "Röd Kaviar", Description = "Röd Kaviar - 24 - 150 g jars",PriceInclusive  = 150,PriceExclusive = 150, QuantityOnHand = 101, Category = seafood, Active = true, Physical = true},
				new Item { Code = "Longlife Tofu", Description = "Longlife Tofu - 5 kg pkg.",PriceInclusive  = 100,PriceExclusive = 100, QuantityOnHand = 4, Category = produce, Active = true, Physical = true},
				new Item { Code = "Rhönbräu Klosterbier", Description = "Rhönbräu Klosterbier - 24 - 0.5 l bottles",PriceInclusive  = 77.5m,PriceExclusive = 77.5m, QuantityOnHand = 125, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Lakkalikööri", Description = "Lakkalikööri - 500 ml",PriceInclusive  = 180,PriceExclusive = 180, QuantityOnHand = 57, Category = beverages, Active = true, Physical = true},
				new Item { Code = "Original Frankfurter grüne Soße", Description = "Original Frankfurter grüne Soße - 12 boxes",PriceInclusive  = 130,PriceExclusive = 130, QuantityOnHand = 32, Category = condiments, Active = true, Physical = true}
			};

			items.ForEach(item => api.ItemRequest.Save(item));
		}

		#endregion

		#endregion

		#region Customers

		[TestMethod]
		public void CreateCustomers()
		{
			var customers = new List<Customer>
			{
				new Customer{Name = "Alfreds Futterkiste",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Maria Anders",DeliveryAddress01 = "Obere Str. 57",DeliveryAddress02 = "Berlin",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "12209",CommunicationMethod = 1,Telephone = "030-0074321",Fax = "030-0076545", SalesRepresentativeId = null},
				new Customer{Name = "Ana Trujillo Emparedados y helados",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Ana Trujillo",DeliveryAddress01 = "Avda. de la Constitución 2222",DeliveryAddress02 = "México D.F.",DeliveryAddress03 = "",DeliveryAddress04 = "Mexico",DeliveryAddress05 = "05021",CommunicationMethod = 1,Telephone = "(5) 555-4729",Fax = "(5) 555-3745", SalesRepresentativeId = null},
				new Customer{Name = "Antonio Moreno Taquería",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Antonio Moreno",DeliveryAddress01 = "Mataderos  2312",DeliveryAddress02 = "México D.F.",DeliveryAddress03 = "",DeliveryAddress04 = "Mexico",DeliveryAddress05 = "05023",CommunicationMethod = 1,Telephone = "(5) 555-3932",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Around the Horn",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Thomas Hardy",DeliveryAddress01 = "120 Hanover Sq.",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "UK",DeliveryAddress05 = "WA1 1DP",CommunicationMethod = 1,Telephone = "(171) 555-7788",Fax = "(171) 555-6750", SalesRepresentativeId = null},
				new Customer{Name = "Berglunds snabbköp",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Christina Berglund",DeliveryAddress01 = "Berguvsvägen  8",DeliveryAddress02 = "Luleå",DeliveryAddress03 = "",DeliveryAddress04 = "Sweden",DeliveryAddress05 = "S-958 22",CommunicationMethod = 1,Telephone = "0921-12 34 65",Fax = "0921-12 34 67", SalesRepresentativeId = null},
				new Customer{Name = "Blauer See Delikatessen",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Hanna Moos",DeliveryAddress01 = "Forsterstr. 57",DeliveryAddress02 = "Mannheim",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "68306",CommunicationMethod = 1,Telephone = "0621-08460",Fax = "0621-08924", SalesRepresentativeId = null},
				new Customer{Name = "Blondesddsl père et fils",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Frédérique Citeaux",DeliveryAddress01 = "24, place Kléber",DeliveryAddress02 = "Strasbourg",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "67000",CommunicationMethod = 1,Telephone = "88.60.15.31",Fax = "88.60.15.32", SalesRepresentativeId = null},
				new Customer{Name = "Bólido Comidas preparadas",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Martín Sommer",DeliveryAddress01 = "C/ Araquil, 67",DeliveryAddress02 = "Madrid",DeliveryAddress03 = "",DeliveryAddress04 = "Spain",DeliveryAddress05 = "28023",CommunicationMethod = 1,Telephone = "(91) 555 22 82",Fax = "(91) 555 91 99", SalesRepresentativeId = null},
				new Customer{Name = "Bon app'",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Laurence Lebihan",DeliveryAddress01 = "12, rue des Bouchers",DeliveryAddress02 = "Marseille",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "13008",CommunicationMethod = 1,Telephone = "91.24.45.40",Fax = "91.24.45.41", SalesRepresentativeId = null},
				new Customer{Name = "Bottom-Dollar Markets",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Elizabeth Lincoln",DeliveryAddress01 = "23 Tsawassen Blvd.",DeliveryAddress02 = "Tsawassen",DeliveryAddress03 = "BC",DeliveryAddress04 = "Canada",DeliveryAddress05 = "T2F 8M4",CommunicationMethod = 1,Telephone = "(604) 555-4729",Fax = "(604) 555-3745", SalesRepresentativeId = null},
				new Customer{Name = "B's Beverages",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Victoria Ashworth",DeliveryAddress01 = "Fauntleroy Circus",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "UK",DeliveryAddress05 = "EC2 5NT",CommunicationMethod = 1,Telephone = "(171) 555-1212",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Cactus Comidas para llevar",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Patricio Simpson",DeliveryAddress01 = "Cerrito 333",DeliveryAddress02 = "Buenos Aires",DeliveryAddress03 = "",DeliveryAddress04 = "Argentina",DeliveryAddress05 = "1010",CommunicationMethod = 1,Telephone = "(1) 135-5555",Fax = "(1) 135-4892", SalesRepresentativeId = null},
				new Customer{Name = "Centro comercial Moctezuma",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Francisco Chang",DeliveryAddress01 = "Sierras de Granada 9993",DeliveryAddress02 = "México D.F.",DeliveryAddress03 = "",DeliveryAddress04 = "Mexico",DeliveryAddress05 = "05022",CommunicationMethod = 1,Telephone = "(5) 555-3392",Fax = "(5) 555-7293", SalesRepresentativeId = null},
				new Customer{Name = "Chop-suey Chinese",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Yang Wang",DeliveryAddress01 = "Hauptstr. 29",DeliveryAddress02 = "Bern",DeliveryAddress03 = "",DeliveryAddress04 = "Switzerland",DeliveryAddress05 = "3012",CommunicationMethod = 1,Telephone = "0452-076545",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Comércio Mineiro",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Pedro Afonso",DeliveryAddress01 = "Av. dos Lusíadas, 23",DeliveryAddress02 = "Sao Paulo",DeliveryAddress03 = "SP",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "05432-043",CommunicationMethod = 1,Telephone = "(11) 555-7647",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Consolidated Holdings",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Elizabeth Brown",DeliveryAddress01 = "Berkeley Gardens 12  Brewery",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "UK",DeliveryAddress05 = "WX1 6LT",CommunicationMethod = 1,Telephone = "(171) 555-2282",Fax = "(171) 555-9199", SalesRepresentativeId = null},
				new Customer{Name = "Drachenblut Delikatessen",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Sven Ottlieb",DeliveryAddress01 = "Walserweg 21",DeliveryAddress02 = "Aachen",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "52066",CommunicationMethod = 1,Telephone = "0241-039123",Fax = "0241-059428", SalesRepresentativeId = null},
				new Customer{Name = "Du monde entier",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Janine Labrune",DeliveryAddress01 = "67, rue des Cinquante Otages",DeliveryAddress02 = "Nantes",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "44000",CommunicationMethod = 1,Telephone = "40.67.88.88",Fax = "40.67.89.89", SalesRepresentativeId = null},
				new Customer{Name = "Eastern Connection",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Ann Devon",DeliveryAddress01 = "35 King George",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "UK",DeliveryAddress05 = "WX3 6FW",CommunicationMethod = 1,Telephone = "(171) 555-0297",Fax = "(171) 555-3373", SalesRepresentativeId = null},
				new Customer{Name = "Ernst Handel",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Roland Mendel",DeliveryAddress01 = "Kirchgasse 6",DeliveryAddress02 = "Graz",DeliveryAddress03 = "",DeliveryAddress04 = "Austria",DeliveryAddress05 = "8010",CommunicationMethod = 1,Telephone = "7675-3425",Fax = "7675-3426", SalesRepresentativeId = null},
				new Customer{Name = "Familia Arquibaldo",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Aria Cruz",DeliveryAddress01 = "Rua Orós, 92",DeliveryAddress02 = "Sao Paulo",DeliveryAddress03 = "SP",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "05442-030",CommunicationMethod = 1,Telephone = "(11) 555-9857",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "FISSA Fabrica Inter. Salchichas S.A.",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Diego Roel",DeliveryAddress01 = "C/ Moralzarzal, 86",DeliveryAddress02 = "Madrid",DeliveryAddress03 = "",DeliveryAddress04 = "Spain",DeliveryAddress05 = "28034",CommunicationMethod = 1,Telephone = "(91) 555 94 44",Fax = "(91) 555 55 93", SalesRepresentativeId = null},
				new Customer{Name = "Folies gourmandes",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Martine Rancé",DeliveryAddress01 = "184, chaussée de Tournai",DeliveryAddress02 = "Lille",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "59000",CommunicationMethod = 1,Telephone = "20.16.10.16",Fax = "20.16.10.17", SalesRepresentativeId = null},
				new Customer{Name = "Folk och fä HB",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Maria Larsson",DeliveryAddress01 = "Åkergatan 24",DeliveryAddress02 = "Bräcke",DeliveryAddress03 = "",DeliveryAddress04 = "Sweden",DeliveryAddress05 = "S-844 67",CommunicationMethod = 1,Telephone = "0695-34 67 21",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Frankenversand",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Peter Franken",DeliveryAddress01 = "Berliner Platz 43",DeliveryAddress02 = "München",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "80805",CommunicationMethod = 1,Telephone = "089-0877310",Fax = "089-0877451", SalesRepresentativeId = null},
				new Customer{Name = "France restauration",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Carine Schmitt",DeliveryAddress01 = "54, rue Royale",DeliveryAddress02 = "Nantes",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "44000",CommunicationMethod = 1,Telephone = "40.32.21.21",Fax = "40.32.21.20", SalesRepresentativeId = null},
				new Customer{Name = "Franchi S.p.A.",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Paolo Accorti",DeliveryAddress01 = "Via Monte Bianco 34",DeliveryAddress02 = "Torino",DeliveryAddress03 = "",DeliveryAddress04 = "Italy",DeliveryAddress05 = "10100",CommunicationMethod = 1,Telephone = "011-4988260",Fax = "011-4988261", SalesRepresentativeId = null},
				new Customer{Name = "Furia Bacalhau e Frutos do Mar",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Lino Rodriguez",DeliveryAddress01 = "Jardim das rosas n. 32",DeliveryAddress02 = "Lisboa",DeliveryAddress03 = "",DeliveryAddress04 = "Portugal",DeliveryAddress05 = "1675",CommunicationMethod = 1,Telephone = "(1) 354-2534",Fax = "(1) 354-2535", SalesRepresentativeId = null},
				new Customer{Name = "Galería del gastrónomo",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Eduardo Saavedra",DeliveryAddress01 = "Rambla de Cataluña, 23",DeliveryAddress02 = "Barcelona",DeliveryAddress03 = "",DeliveryAddress04 = "Spain",DeliveryAddress05 = "08022",CommunicationMethod = 1,Telephone = "(93) 203 4560",Fax = "(93) 203 4561", SalesRepresentativeId = null},
				new Customer{Name = "Godos Cocina Típica",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "José Pedro Freyre",DeliveryAddress01 = "C/ Romero, 33",DeliveryAddress02 = "Sevilla",DeliveryAddress03 = "",DeliveryAddress04 = "Spain",DeliveryAddress05 = "41101",CommunicationMethod = 1,Telephone = "(95) 555 82 82",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Gourmet Lanchonetes",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "André Fonseca",DeliveryAddress01 = "Av. Brasil, 442",DeliveryAddress02 = "Campinas",DeliveryAddress03 = "SP",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "04876-786",CommunicationMethod = 1,Telephone = "(11) 555-9482",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Great Lakes Food Market",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Howard Snyder",DeliveryAddress01 = "2732 Baker Blvd.",DeliveryAddress02 = "Eugene",DeliveryAddress03 = "OR",DeliveryAddress04 = "USA",DeliveryAddress05 = "97403",CommunicationMethod = 1,Telephone = "(503) 555-7555",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "GROSELLA-Restaurante",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Manuel Pereira",DeliveryAddress01 = "5ª Ave. Los Palos Grandes",DeliveryAddress02 = "Caracas",DeliveryAddress03 = "DF",DeliveryAddress04 = "Venezuela",DeliveryAddress05 = "1081",CommunicationMethod = 1,Telephone = "(2) 283-2951",Fax = "(2) 283-3397", SalesRepresentativeId = null},
				new Customer{Name = "Hanari Carnes",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Mario Pontes",DeliveryAddress01 = "Rua do Paço, 67",DeliveryAddress02 = "Rio de Janeiro",DeliveryAddress03 = "RJ",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "05454-876",CommunicationMethod = 1,Telephone = "(21) 555-0091",Fax = "(21) 555-8765", SalesRepresentativeId = null},
				new Customer{Name = "HILARION-Abastos",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Carlos Hernández",DeliveryAddress01 = "Carrera 22 con Ave. Carlos Soublette #8-35",DeliveryAddress02 = "San Cristóbal",DeliveryAddress03 = "Táchira",DeliveryAddress04 = "Venezuela",DeliveryAddress05 = "5022",CommunicationMethod = 1,Telephone = "(5) 555-1340",Fax = "(5) 555-1948", SalesRepresentativeId = null},
				new Customer{Name = "Hungry Coyote Import Store",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Yoshi Latimer",DeliveryAddress01 = "City Center Plaza 516 Main St.",DeliveryAddress02 = "Elgin",DeliveryAddress03 = "OR",DeliveryAddress04 = "USA",DeliveryAddress05 = "97827",CommunicationMethod = 1,Telephone = "(503) 555-6874",Fax = "(503) 555-2376", SalesRepresentativeId = null},
				new Customer{Name = "Hungry Owl All-Night Grocers",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Patricia McKenna",DeliveryAddress01 = "8 Johnstown Road",DeliveryAddress02 = "Cork",DeliveryAddress03 = "Co. Cork",DeliveryAddress04 = "Ireland",DeliveryAddress05 = "",CommunicationMethod = 1,Telephone = "2967 542",Fax = "2967 3333", SalesRepresentativeId = null},
				new Customer{Name = "Island Trading",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Helen Bennett",DeliveryAddress01 = "Garden House Crowther Way",DeliveryAddress02 = "Cowes",DeliveryAddress03 = "Isle of Wight",DeliveryAddress04 = "UK",DeliveryAddress05 = "PO31 7PJ",CommunicationMethod = 1,Telephone = "(198) 555-8888",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Königlich Essen",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Philip Cramer",DeliveryAddress01 = "Maubelstr. 90",DeliveryAddress02 = "Brandenburg",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "14776",CommunicationMethod = 1,Telephone = "0555-09876",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "La corne d'abondance",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Daniel Tonini",DeliveryAddress01 = "67, avenue de l'Europe",DeliveryAddress02 = "Versailles",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "78000",CommunicationMethod = 1,Telephone = "30.59.84.10",Fax = "30.59.85.11", SalesRepresentativeId = null},
				new Customer{Name = "La maison d'Asie",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Annette Roulet",DeliveryAddress01 = "1 rue Alsace-Lorraine",DeliveryAddress02 = "Toulouse",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "31000",CommunicationMethod = 1,Telephone = "61.77.61.10",Fax = "61.77.61.11", SalesRepresentativeId = null},
				new Customer{Name = "Laughing Bacchus Wine Cellars",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Yoshi Tannamuri",DeliveryAddress01 = "1900 Oak St.",DeliveryAddress02 = "Vancouver",DeliveryAddress03 = "BC",DeliveryAddress04 = "Canada",DeliveryAddress05 = "V3F 2K1",CommunicationMethod = 1,Telephone = "(604) 555-3392",Fax = "(604) 555-7293", SalesRepresentativeId = null},
				new Customer{Name = "Lazy K Kountry Store",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "John Steel",DeliveryAddress01 = "12 Orchestra Terrace",DeliveryAddress02 = "Walla Walla",DeliveryAddress03 = "WA",DeliveryAddress04 = "USA",DeliveryAddress05 = "99362",CommunicationMethod = 1,Telephone = "(509) 555-7969",Fax = "(509) 555-6221", SalesRepresentativeId = null},
				new Customer{Name = "Lehmanns Marktstand",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Renate Messner",DeliveryAddress01 = "Magazinweg 7",DeliveryAddress02 = "Frankfurt a.M.",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "60528",CommunicationMethod = 1,Telephone = "069-0245984",Fax = "069-0245874", SalesRepresentativeId = null},
				new Customer{Name = "Let's Stop N Shop",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Jaime Yorres",DeliveryAddress01 = "87 Polk St. Suite 5",DeliveryAddress02 = "San Francisco",DeliveryAddress03 = "CA",DeliveryAddress04 = "USA",DeliveryAddress05 = "94117",CommunicationMethod = 1,Telephone = "(415) 555-5938",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "LILA-Supermercado",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Carlos González",DeliveryAddress01 = "Carrera 52 con Ave. Bolívar #65-98 Llano Largo",DeliveryAddress02 = "Barquisimeto",DeliveryAddress03 = "Lara",DeliveryAddress04 = "Venezuela",DeliveryAddress05 = "3508",CommunicationMethod = 1,Telephone = "(9) 331-6954",Fax = "(9) 331-7256", SalesRepresentativeId = null},
				new Customer{Name = "LINO-Delicateses",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Felipe Izquierdo",DeliveryAddress01 = "Ave. 5 de Mayo Porlamar",DeliveryAddress02 = "I. de Margarita",DeliveryAddress03 = "Nueva Esparta",DeliveryAddress04 = "Venezuela",DeliveryAddress05 = "4980",CommunicationMethod = 1,Telephone = "(8) 34-56-12",Fax = "(8) 34-93-93", SalesRepresentativeId = null},
				new Customer{Name = "Lonesome Pine Restaurant",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Fran Wilson",DeliveryAddress01 = "89 Chiaroscuro Rd.",DeliveryAddress02 = "Portland",DeliveryAddress03 = "OR",DeliveryAddress04 = "USA",DeliveryAddress05 = "97219",CommunicationMethod = 1,Telephone = "(503) 555-9573",Fax = "(503) 555-9646", SalesRepresentativeId = null},
				new Customer{Name = "Magazzini Alimentari Riuniti",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Giovanni Rovelli",DeliveryAddress01 = "Via Ludovico il Moro 22",DeliveryAddress02 = "Bergamo",DeliveryAddress03 = "",DeliveryAddress04 = "Italy",DeliveryAddress05 = "24100",CommunicationMethod = 1,Telephone = "035-640230",Fax = "035-640231", SalesRepresentativeId = null},
				new Customer{Name = "Maison Dewey",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Catherine Dewey",DeliveryAddress01 = "Rue Joseph-Bens 532",DeliveryAddress02 = "Bruxelles",DeliveryAddress03 = "",DeliveryAddress04 = "Belgium",DeliveryAddress05 = "B-1180",CommunicationMethod = 1,Telephone = "(02) 201 24 67",Fax = "(02) 201 24 68", SalesRepresentativeId = null},
				new Customer{Name = "Mère Paillarde",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Jean Fresnière",DeliveryAddress01 = "43 rue St. Laurent",DeliveryAddress02 = "Montréal",DeliveryAddress03 = "Québec",DeliveryAddress04 = "Canada",DeliveryAddress05 = "H1J 1C3",CommunicationMethod = 1,Telephone = "(514) 555-8054",Fax = "(514) 555-8055", SalesRepresentativeId = null},
				new Customer{Name = "Morgenstern Gesundkost",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Alexander Feuer",DeliveryAddress01 = "Heerstr. 22",DeliveryAddress02 = "Leipzig",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "04179",CommunicationMethod = 1,Telephone = "0342-023176",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "North/South",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Simon Crowther",DeliveryAddress01 = "South House 300 Queensbridge",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "UK",DeliveryAddress05 = "SW7 1RZ",CommunicationMethod = 1,Telephone = "(171) 555-7733",Fax = "(171) 555-2530", SalesRepresentativeId = null},
				new Customer{Name = "Océano Atlántico Ltda.",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Yvonne Moncada",DeliveryAddress01 = "Ing. Gustavo Moncada 8585 Piso 20-A",DeliveryAddress02 = "Buenos Aires",DeliveryAddress03 = "",DeliveryAddress04 = "Argentina",DeliveryAddress05 = "1010",CommunicationMethod = 1,Telephone = "(1) 135-5333",Fax = "(1) 135-5535", SalesRepresentativeId = null},
				new Customer{Name = "Old World Delicatessen",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Rene Phillips",DeliveryAddress01 = "2743 Bering St.",DeliveryAddress02 = "Anchorage",DeliveryAddress03 = "AK",DeliveryAddress04 = "USA",DeliveryAddress05 = "99508",CommunicationMethod = 1,Telephone = "(907) 555-7584",Fax = "(907) 555-2880", SalesRepresentativeId = null},
				new Customer{Name = "Ottilies Käseladen",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Henriette Pfalzheim",DeliveryAddress01 = "Mehrheimerstr. 369",DeliveryAddress02 = "Köln",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "50739",CommunicationMethod = 1,Telephone = "0221-0644327",Fax = "0221-0765721", SalesRepresentativeId = null},
				new Customer{Name = "Paris spécialités",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Marie Bertrand",DeliveryAddress01 = "265, boulevard Charonne",DeliveryAddress02 = "Paris",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "75012",CommunicationMethod = 1,Telephone = "(1) 42.34.22.66",Fax = "(1) 42.34.22.77", SalesRepresentativeId = null},
				new Customer{Name = "Pericles Comidas clásicas",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Guillermo Fernández",DeliveryAddress01 = "Calle Dr. Jorge Cash 321",DeliveryAddress02 = "México D.F.",DeliveryAddress03 = "",DeliveryAddress04 = "Mexico",DeliveryAddress05 = "05033",CommunicationMethod = 1,Telephone = "(5) 552-3745",Fax = "(5) 545-3745", SalesRepresentativeId = null},
				new Customer{Name = "Piccolo und mehr",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Georg Pipps",DeliveryAddress01 = "Geislweg 14",DeliveryAddress02 = "Salzburg",DeliveryAddress03 = "",DeliveryAddress04 = "Austria",DeliveryAddress05 = "5020",CommunicationMethod = 1,Telephone = "6562-9722",Fax = "6562-9723", SalesRepresentativeId = null},
				new Customer{Name = "Princesa Isabel Vinhos",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Isabel de Castro",DeliveryAddress01 = "Estrada da saúde n. 58",DeliveryAddress02 = "Lisboa",DeliveryAddress03 = "",DeliveryAddress04 = "Portugal",DeliveryAddress05 = "1756",CommunicationMethod = 1,Telephone = "(1) 356-5634",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Que Delícia",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Bernardo Batista",DeliveryAddress01 = "Rua da Panificadora, 12",DeliveryAddress02 = "Rio de Janeiro",DeliveryAddress03 = "RJ",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "02389-673",CommunicationMethod = 1,Telephone = "(21) 555-4252",Fax = "(21) 555-4545", SalesRepresentativeId = null},
				new Customer{Name = "Queen Cozinha",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Lúcia Carvalho",DeliveryAddress01 = "Alameda dos Canàrios, 891",DeliveryAddress02 = "Sao Paulo",DeliveryAddress03 = "SP",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "05487-020",CommunicationMethod = 1,Telephone = "(11) 555-1189",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "QUICK-Stop",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Horst Kloss",DeliveryAddress01 = "Taucherstraße 10",DeliveryAddress02 = "Cunewalde",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "01307",CommunicationMethod = 1,Telephone = "0372-035188",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Rancho grande",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Sergio Gutiérrez",DeliveryAddress01 = "Av. del Libertador 900",DeliveryAddress02 = "Buenos Aires",DeliveryAddress03 = "",DeliveryAddress04 = "Argentina",DeliveryAddress05 = "1010",CommunicationMethod = 1,Telephone = "(1) 123-5555",Fax = "(1) 123-5556", SalesRepresentativeId = null},
				new Customer{Name = "Rattlesnake Canyon Grocery",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Paula Wilson",DeliveryAddress01 = "2817 Milton Dr.",DeliveryAddress02 = "Albuquerque",DeliveryAddress03 = "NM",DeliveryAddress04 = "USA",DeliveryAddress05 = "87110",CommunicationMethod = 1,Telephone = "(505) 555-5939",Fax = "(505) 555-3620", SalesRepresentativeId = null},
				new Customer{Name = "Reggiani Caseifici",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Maurizio Moroni",DeliveryAddress01 = "Strada Provinciale 124",DeliveryAddress02 = "Reggio Emilia",DeliveryAddress03 = "",DeliveryAddress04 = "Italy",DeliveryAddress05 = "42100",CommunicationMethod = 1,Telephone = "0522-556721",Fax = "0522-556722", SalesRepresentativeId = null},
				new Customer{Name = "Ricardo Adocicados",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Janete Limeira",DeliveryAddress01 = "Av. Copacabana, 267",DeliveryAddress02 = "Rio de Janeiro",DeliveryAddress03 = "RJ",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "02389-890",CommunicationMethod = 1,Telephone = "(21) 555-3412",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Richter Supermarkt",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Michael Holz",DeliveryAddress01 = "Grenzacherweg 237",DeliveryAddress02 = "Genève",DeliveryAddress03 = "",DeliveryAddress04 = "Switzerland",DeliveryAddress05 = "1203",CommunicationMethod = 1,Telephone = "0897-034214",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Romero y tomillo",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Alejandra Camino",DeliveryAddress01 = "Gran Vía, 1",DeliveryAddress02 = "Madrid",DeliveryAddress03 = "",DeliveryAddress04 = "Spain",DeliveryAddress05 = "28001",CommunicationMethod = 1,Telephone = "(91) 745 6200",Fax = "(91) 745 6210", SalesRepresentativeId = null},
				new Customer{Name = "Santé Gourmet",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Jonas Bergulfsen",DeliveryAddress01 = "Erling Skakkes gate 78",DeliveryAddress02 = "Stavern",DeliveryAddress03 = "",DeliveryAddress04 = "Norway",DeliveryAddress05 = "4110",CommunicationMethod = 1,Telephone = "07-98 92 35",Fax = "07-98 92 47", SalesRepresentativeId = null},
				new Customer{Name = "Save-a-lot Markets",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Jose Pavarotti",DeliveryAddress01 = "187 Suffolk Ln.",DeliveryAddress02 = "Boise",DeliveryAddress03 = "ID",DeliveryAddress04 = "USA",DeliveryAddress05 = "83720",CommunicationMethod = 1,Telephone = "(208) 555-8097",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Seven Seas Imports",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Hari Kumar",DeliveryAddress01 = "90 Wadhurst Rd.",DeliveryAddress02 = "London",DeliveryAddress03 = "",DeliveryAddress04 = "UK",DeliveryAddress05 = "OX15 4NB",CommunicationMethod = 1,Telephone = "(171) 555-1717",Fax = "(171) 555-5646", SalesRepresentativeId = null},
				new Customer{Name = "Simons bistro",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Jytte Petersen",DeliveryAddress01 = "Vinbæltet 34",DeliveryAddress02 = "Kobenhavn",DeliveryAddress03 = "",DeliveryAddress04 = "Denmark",DeliveryAddress05 = "1734",CommunicationMethod = 1,Telephone = "31 12 34 56",Fax = "31 13 35 57", SalesRepresentativeId = null},
				new Customer{Name = "Spécialités du monde",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Dominique Perrier",DeliveryAddress01 = "25, rue Lauriston",DeliveryAddress02 = "Paris",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "75016",CommunicationMethod = 1,Telephone = "(1) 47.55.60.10",Fax = "(1) 47.55.60.20", SalesRepresentativeId = null},
				new Customer{Name = "Split Rail Beer & Ale",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Art Braunschweiger",DeliveryAddress01 = "P.O. Box 555",DeliveryAddress02 = "Lander",DeliveryAddress03 = "WY",DeliveryAddress04 = "USA",DeliveryAddress05 = "82520",CommunicationMethod = 1,Telephone = "(307) 555-4680",Fax = "(307) 555-6525", SalesRepresentativeId = null},
				new Customer{Name = "Suprêmes délices",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Pascale Cartrain",DeliveryAddress01 = "Boulevard Tirou, 255",DeliveryAddress02 = "Charleroi",DeliveryAddress03 = "",DeliveryAddress04 = "Belgium",DeliveryAddress05 = "B-6000",CommunicationMethod = 1,Telephone = "(071) 23 67 22 20",Fax = "(071) 23 67 22 21", SalesRepresentativeId = null},
				new Customer{Name = "The Big Cheese",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Liz Nixon",DeliveryAddress01 = "89 Jefferson Way Suite 2",DeliveryAddress02 = "Portland",DeliveryAddress03 = "OR",DeliveryAddress04 = "USA",DeliveryAddress05 = "97201",CommunicationMethod = 1,Telephone = "(503) 555-3612",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "The Cracker Box",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Liu Wong",DeliveryAddress01 = "55 Grizzly Peak Rd.",DeliveryAddress02 = "Butte",DeliveryAddress03 = "MT",DeliveryAddress04 = "USA",DeliveryAddress05 = "59801",CommunicationMethod = 1,Telephone = "(406) 555-5834",Fax = "(406) 555-8083", SalesRepresentativeId = null},
				new Customer{Name = "Toms Spezialitäten",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Karin Josephs",DeliveryAddress01 = "Luisenstr. 48",DeliveryAddress02 = "Münster",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "44087",CommunicationMethod = 1,Telephone = "0251-031259",Fax = "0251-035695", SalesRepresentativeId = null},
				new Customer{Name = "Tortuga Restaurante",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Miguel Angel Paolino",DeliveryAddress01 = "Avda. Azteca 123",DeliveryAddress02 = "México D.F.",DeliveryAddress03 = "",DeliveryAddress04 = "Mexico",DeliveryAddress05 = "05033",CommunicationMethod = 1,Telephone = "(5) 555-2933",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "Tradição Hipermercados",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Anabela Domingues",DeliveryAddress01 = "Av. Inês de Castro, 414",DeliveryAddress02 = "Sao Paulo",DeliveryAddress03 = "SP",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "05634-030",CommunicationMethod = 1,Telephone = "(11) 555-2167",Fax = "(11) 555-2168", SalesRepresentativeId = null},
				new Customer{Name = "Trail's Head Gourmet Provisioners",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Helvetius Nagy",DeliveryAddress01 = "722 DaVinci Blvd.",DeliveryAddress02 = "Kirkland",DeliveryAddress03 = "WA",DeliveryAddress04 = "USA",DeliveryAddress05 = "98034",CommunicationMethod = 1,Telephone = "(206) 555-8257",Fax = "(206) 555-2174", SalesRepresentativeId = null},
				new Customer{Name = "Vaffeljernet",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Palle Ibsen",DeliveryAddress01 = "Smagsloget 45",DeliveryAddress02 = "Århus",DeliveryAddress03 = "",DeliveryAddress04 = "Denmark",DeliveryAddress05 = "8200",CommunicationMethod = 1,Telephone = "86 21 32 43",Fax = "86 22 33 44", SalesRepresentativeId = null},
				new Customer{Name = "Victuailles en stock",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Mary Saveley",DeliveryAddress01 = "2, rue du Commerce",DeliveryAddress02 = "Lyon",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "69004",CommunicationMethod = 1,Telephone = "78.32.54.86",Fax = "78.32.54.87", SalesRepresentativeId = null},
				new Customer{Name = "Vins et alcools Chevalier",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Paul Henriot",DeliveryAddress01 = "59 rue de l'Abbaye",DeliveryAddress02 = "Reims",DeliveryAddress03 = "",DeliveryAddress04 = "France",DeliveryAddress05 = "51100",CommunicationMethod = 1,Telephone = "26.47.15.10",Fax = "26.47.15.11", SalesRepresentativeId = null},
				new Customer{Name = "Die Wandernde Kuh",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Rita Müller",DeliveryAddress01 = "Adenauerallee 900",DeliveryAddress02 = "Stuttgart",DeliveryAddress03 = "",DeliveryAddress04 = "Germany",DeliveryAddress05 = "70563",CommunicationMethod = 1,Telephone = "0711-020361",Fax = "0711-035428", SalesRepresentativeId = null},
				new Customer{Name = "Wartian Herkku",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Pirkko Koskitalo",DeliveryAddress01 = "Torikatu 38",DeliveryAddress02 = "Oulu",DeliveryAddress03 = "",DeliveryAddress04 = "Finland",DeliveryAddress05 = "90110",CommunicationMethod = 1,Telephone = "981-443655",Fax = "981-443655", SalesRepresentativeId = null},
				new Customer{Name = "Wellington Importadora",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Paula Parente",DeliveryAddress01 = "Rua do Mercado, 12",DeliveryAddress02 = "Resende",DeliveryAddress03 = "SP",DeliveryAddress04 = "Brazil",DeliveryAddress05 = "08737-363",CommunicationMethod = 1,Telephone = "(14) 555-8122",Fax = "", SalesRepresentativeId = null},
				new Customer{Name = "White Clover Markets",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Karl Jablonski",DeliveryAddress01 = "305 - 14th Ave. S. Suite 3B",DeliveryAddress02 = "Seattle",DeliveryAddress03 = "WA",DeliveryAddress04 = "USA",DeliveryAddress05 = "98128",CommunicationMethod = 1,Telephone = "(206) 555-4112",Fax = "(206) 555-4115", SalesRepresentativeId = null},
				new Customer{Name = "Wilman Kala",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Matti Karttunen",DeliveryAddress01 = "Keskuskatu 45",DeliveryAddress02 = "Helsinki",DeliveryAddress03 = "",DeliveryAddress04 = "Finland",DeliveryAddress05 = "21240",CommunicationMethod = 1,Telephone = "90-224 8858",Fax = "90-224 8858", SalesRepresentativeId = null},
				new Customer{Name = "Wolski  Zajazd",AcceptsElectronicInvoices = true,Active = true,AutoAllocateToOldestInvoice = true,Balance = 0,ContactName = "Zbyszek Piestrzeniewicz",DeliveryAddress01 = "ul. Filtrowa 68",DeliveryAddress02 = "Warszawa",DeliveryAddress03 = "",DeliveryAddress04 = "Poland",DeliveryAddress05 = "01-012",CommunicationMethod = 1,Telephone = "(26) 642-7012",Fax = "(26) 642-7012", SalesRepresentativeId = null}
			};

			var api = new ApiRequest(Username, Password, Apikey, CompanyId);

			foreach (var cust in customers)
			{
				cust.PostalAddress01 = cust.DeliveryAddress01;
				cust.PostalAddress02 = cust.DeliveryAddress02;
				cust.PostalAddress03 = cust.DeliveryAddress03;
				cust.PostalAddress04 = cust.DeliveryAddress04;
				cust.PostalAddress05 = cust.DeliveryAddress05;
			}

			customers.ForEach(cust => api.CustomerRequest.Save(cust));
		}

		#endregion
	}
}
